'use client';

import { use } from 'react';
import Image from 'next/image';
import CourseDetailsBanner from '@/components/public/course-details/CourseDetailsBanner';
import CourseDetailsNavigation from '@/components/public/course-details/CourseDetailsNavigation';
import CourseOverviewSection from '@/components/public/course-details/CourseOverviewSection';
import CourseContentSection from '@/components/public/course-details/CourseContentSection';
import CourseDetailsInfoSection from '@/components/public/course-details/CourseDetailsInfoSection';
import CourseInstructorSection from '@/components/public/course-details/CourseInstructorSection';
import CourseReviewSection from '@/components/public/course-details/CourseReviewSection';
import CourseSidebar from '@/components/public/course-details/CourseSidebar';
import CourseCard from '@/components/public/course/CourseCard';

/**
 * Course Details Page
 * Template content converted to React components
 */
export default function CourseDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);

  // Dummy course data - will be replaced with API call
  const course = {
    id,
    title: 'Study Score AI Premium: The Ultimate Adaptive Exam Prep',
    description: 'Stop guessing, start improving. Your personal AI Tutor analyzes your unique learning style to create a dynamic roadmap for IELTS, TOEFL, SAT, and more.',
    rating: 4.9,
    totalRatings: 12540,
    totalStudents: 45000,
    author: {
      name: 'Study Score Team',
      avatar: '/assets/images/client/avatar-02.png', // Logo olabilir
      profileLink: '/profile',
    },
    category: 'Exam Preparation',
    lastUpdated: '01/2026',
    language: 'English',
    isCertified: true,
    isBestseller: true,
    thumbnail: '/assets/images/course/course-01.jpg', // Ürün görseli
    currentPrice: '$49.99',
    oldPrice: '$199.99',
    discountDays: 5,
    videoPreview: {
      thumbnail: '/assets/images/others/video-01.jpg',
      videoUrl: 'https://www.youtube.com/watch?v=nA1Aqp0sPQo', // Tanıtım videosu linki
    },
    learningPoints: [
      'Get a personalized study roadmap generated by AI based on your initial diagnostic test.',
      'Receive instant, microscopic feedback on Writing essays and Speaking tasks.',
      'Master exam strategies for IELTS, TOEFL, and SAT with adaptive difficulty levels.',
      'Identify and fix your "hidden" weak points that standard courses miss.',
      'Practice with realistic exam simulations that mimic actual test conditions.',
      'Track your progress with real-time data analytics and score predictions.',
      'Learn efficiently by skipping topics you already know (Auto-Learning).',
      'Access your private AI tutor 24/7, anywhere, anytime.',
    ],
    extendedDescription: 'Forget the "one-size-fits-all" approach of traditional classrooms. Study Score AI is the Tesla of exam preparation. Our fine-tuned AI models understand the specific rubrics of international exams (IELTS, TOEFL, SAT) better than any human tutor. Whether you are stuck at a specific band score or just starting, our "Smart Tutor" engine constantly adapts the curriculum to your performance. It’s not just about studying harder; it’s about studying smarter with data-driven precision.',
    sections: [
      {
        id: 'intro',
        title: 'Phase 1: Diagnostic & Strategy',
        duration: '2hr 15min',
        lessons: [
          {
            id: '1',
            title: 'Welcome to the AI Era of Learning',
            duration: '10 min',
            type: 'video' as const,
            isPreview: true,
          },
          {
            id: '2',
            title: 'Initial AI Diagnostic Test',
            duration: '60 min',
            type: 'video' as const, // Burası 'quiz' type olabilir sistem destekliyorsa
            isPreview: false,
          },
          {
            id: '3',
            title: 'Your Personalized Roadmap Reveal',
            type: 'text' as const,
            isLocked: true,
          },
        ],
      },
      {
        id: 'fundamentals',
        title: 'Phase 2: Adaptive Modules (Weakness Focus)',
        duration: 'Adaptive Duration',
        lessons: [
          {
            id: '4',
            title: 'Micro-Skill: Advanced Coherence in Writing',
            type: 'video' as const,
            isLocked: true,
          },
          {
            id: '5',
            title: 'Simulation: Speaking Part 2 with AI Feedback',
            type: 'text' as const, // Uygulama modülü
            isLocked: true,
          },
        ],
      },
    ],
    requirements: [
      'A goal to succeed in IELTS, TOEFL, SAT, or similar international exams.',
      'Basic English proficiency (A2 level or higher recommended).',
      'A computer or tablet with internet access.',
      'A microphone for Speaking simulations.',
    ],
    detailsDescription: [
      'Full access to the Multi-Modal Assessment Engine (Writing, Speaking, Listening, Reading).',
      'Unlimited essay grading with detailed corrections on grammar, vocabulary, and flow.',
      'Real-time pronunciation and fluency analysis for speaking tasks.',
      'Access to our database of 10,000+ adaptive questions.',
    ],
    instructor: {
      name: 'Dr. Murat Koçar',
      avatar: '/assets/images/testimonial/testimonial-7.jpg',
      profileLink: '/author',
      title: 'Founder & AI Visionary',
      rating: 4.9,
      totalReviews: 1205,
      totalStudents: 45000,
      totalCourses: 1,
      bio: 'Dr. Tekkaya is the visionary behind Study Score AI. With a passion for democratizing elite education, he leads the team developing the world\'s most advanced "Smart Tutor" technology.',
      socialLinks: {
        facebook: 'https://www.facebook.com/',
        twitter: 'https://www.twitter.com',
        instagram: 'https://www.instagram.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    },
    ratingBreakdown: [
      { stars: 5, percentage: 85 },
      { stars: 4, percentage: 10 },
      { stars: 3, percentage: 3 },
      { stars: 2, percentage: 1 },
      { stars: 1, percentage: 1 },
    ],
    featuredReviews: [
      {
        id: '1',
        author: {
          name: 'Zeynep Yilmaz',
          avatar: '/assets/images/testimonial/testimonial-3.jpg',
          profileLink: '/profile',
        },
        rating: 5,
        comment: 'I was stuck at 6.5 in IELTS writing for months. The AI pointed out exactly why I was losing points on "Task Response". I got an 8.0 in just 3 weeks!',
      },
      {
        id: '2',
        author: {
          name: 'Michael Chen',
          avatar: '/assets/images/testimonial/testimonial-8.jpg',
          profileLink: '/profile',
        },
        rating: 5,
        comment: 'The SAT math simulations are harder than the real thing, which made the actual exam feel easy. The adaptive learning path saved me so much time.',
      },
    ],
    courseFeatures: [
      { label: 'Access', value: 'Lifetime / Subscription' },
      { label: 'AI Tutor', value: '24/7 Available' },
      { label: 'Exams', value: 'IELTS, TOEFL, SAT+' },
      { label: 'Skill Level', value: 'Adaptive' },
      { label: 'Language', value: 'English' },
      { label: 'Simulations', value: 'Unlimited' },
      { label: 'Certificate', value: 'Completion' },
      { label: 'Score Guarantee', value: 'Yes*' },
    ],
    relatedCourses: [
      {
        id: '1',
        image: '/assets/images/course/course-online-01.jpg',
        title: 'IELTS Speaking Masterclass: AI Edition',
        description: 'Focus solely on maximizing your speaking score with instant AI feedback.',
        lessons: 20,
        students: 1200,
        rating: 4.8,
        reviews: 350,
        author: {
          name: 'Study Score AI',
          avatar: '/assets/images/client/avatar-02.png',
          profileLink: '/profile',
        },
        category: 'Speaking Prep',
        currentPrice: '$29.99',
        oldPrice: '$59.99',
        discount: '-50%',
      },
      {
        id: '2',
        image: '/assets/images/course/course-online-02.jpg',
        title: 'SAT Digital: Math & Logic Booster',
        description: 'An intensive adaptive course for the math section of the new Digital SAT.',
        lessons: 15,
        students: 850,
        rating: 4.9,
        reviews: 210,
        author: {
          name: 'Study Score AI',
          avatar: '/assets/images/client/avatar-02.png',
          profileLink: '/profile',
        },
        category: 'Math Prep',
        currentPrice: '$29.99',
        oldPrice: '$59.99',
        showAddToCart: true,
      },
    ],
  };

  const handleAddToCart = () => {
    console.log('Add to cart:', course.id);
    // TODO: Implement add to cart
  };

  const handleBuyNow = () => {
    console.log('Buy now:', course.id);
    // TODO: Implement buy now
  };

  return (
    <>
      {/* Course Details Banner */}
      <CourseDetailsBanner
        title={course.title}
        description={course.description}
        rating={course.rating}
        totalRatings={course.totalRatings}
        totalStudents={course.totalStudents}
        author={course.author}
        category={course.category}
        lastUpdated={course.lastUpdated}
        language={course.language}
        isCertified={course.isCertified}
        isBestseller={course.isBestseller}
      />

      <div className="rbt-course-details-area ptb--60">
        <div className="container">
          <div className="row g-5">
            {/* Main Content */}
            <div className="col-lg-8">
              <div className="course-details-content">
                {/* Course Thumbnail */}
                <div className="rbt-course-feature-box rbt-shadow-box thuumbnail">
                  <Image
                    className="w-100"
                    src={course.thumbnail}
                    alt={course.title}
                    width={800}
                    height={450}
                    style={{ objectFit: 'cover' }}
                  />
                </div>

                {/* Sticky Navigation */}
                <CourseDetailsNavigation />

                {/* Overview Section */}
                <CourseOverviewSection
                  description={course.description}
                  learningPoints={course.learningPoints}
                  extendedDescription={course.extendedDescription}
                />

                {/* Course Content Section */}
                <CourseContentSection sections={course.sections} />

                {/* Details Section */}
                <CourseDetailsInfoSection
                  requirements={course.requirements}
                  description={course.detailsDescription}
                />

                {/* Instructor Section */}
                <CourseInstructorSection instructor={course.instructor} />

                {/* Review Section */}
                <CourseReviewSection
                  averageRating={course.rating}
                  totalRatings={course.totalRatings}
                  ratingBreakdown={course.ratingBreakdown}
                  featuredReviews={course.featuredReviews}
                />

                {/* Related Courses */}
                <div className="related-course mt--60">
                  <div className="row g-5 align-items-end mb--40">
                    <div className="col-lg-8 col-md-8 col-12">
                      <div className="section-title">
                        <span className="subtitle bg-pink-opacity">Top Course</span>
                        <h4 className="title">
                          More Course By <strong className="color-primary">{course.author.name}</strong>
                        </h4>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-12">
                      <div className="read-more-btn text-start text-md-end">
                        <a className="rbt-btn rbt-switch-btn btn-border btn-sm" href="/courses">
                          <span data-text="View All Course">View All Course</span>
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="row g-5">
                    {course.relatedCourses.map((relatedCourse) => (
                      <div key={relatedCourse.id} className="col-lg-6 col-md-6 col-sm-6 col-12">
                        <CourseCard {...relatedCourse} />
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <CourseSidebar
              currentPrice={course.currentPrice}
              oldPrice={course.oldPrice}
              discountDays={course.discountDays}
              videoPreview={course.videoPreview}
              courseFeatures={course.courseFeatures}
              onAddToCart={handleAddToCart}
              onBuyNow={handleBuyNow}
            />
          </div>
        </div>
      </div>
    </>
  );
}

